alias l='ls'
alias la='ls -a'
alias ..='cd ..'

alias gst='git status'
alias gc="git commit -m" 
alias ga="git add "
alias gp="git push "
alias gr="git rm "
alias gl="git log --graph --decorate --pretty=oneline --abbrev-commit --all --date=local"


